### ISSUE TITLE
Suggestion: Update README with Testem Option

### ISSUE THREAD

**Issue by Matt-Jensen** [mydea/actions-ember-testing#1]
In order to get this action to work with a new ember app I had to add `browser_start_timeout: 60` to my testem configuration because it was timing out after 30 seconds.  I'd suggest making a note of this in README if you think it's a common enough issue.

Aside from that this action is great! Thank you for creating it.

**Comment by mydea** [comment]
Hmm, I didn't need this setting myself - but the tests to time out randomly sometimes for me, so that might be the issue here. I'd be up for a PR including something along the lines of "If you find your tests timing out on GH Actions, extended the timeout time..."!

**Comment by mydea** [comment]
I added this now to the readme, thanks :)
